#EVM DM365 packages preferences

PREFERRED_VERSION_ti-codec-engine = "2_26_02_11"
PREFERRED_VERSION_ti-codec-engine-examples = "2_26_02_11"

#PREFERRED_VERSION_ti-cgt6x = "6_1_14"
PREFERRED_VERSION_ti-framework-components = "2_26_00_01"
PREFERRED_VERSION_ti-linuxutils = "2_26_01_02"
PREFERRED_VERSION_ti-local-power-manager = "1_24_02_09"
PREFERRED_VERSION_ti-lpm-module = "1_24_02_09"
PREFERRED_VERSION_ti-lpm-utils = "1_24_02_09"
PREFERRED_VERSION_ti-xdais = "6_26_01_03"
PREFERRED_VERSION_ti-xdctools = "3_16_03_36"

PREFERRED_VERSION_ti-codecs-dm365 = "4_02_00_00"
PREFERRED_VERSION_ti-codecs-dm365-server = "4_02_00_00"
PREFERRED_VERSION_ti-dm365mm-module = "01_00_03"
PREFERRED_VERSION_ti-dvsdk-demos = "4_02_00_01"

PREFERRED_VERSION_ti-dmai = "2_20_00_15"
PREFERRED_VERSION_ti-dmai-apps = "2_20_00_15"
PREFERRED_VERSION_ti-dmai-tests = "2_20_00_15"

PREFERRED_VERSION_gstreamer-ti = "svnr919"
PREFERRED_VERSION_gstreamer-ti-demo-script = "svnr919"
