################################################################################
# Arago SDK target software task definition                                    #
#                                                                              #
# Author: Andrei Mironenko <andrei.mironenko@paralleldynamic.com>              #
#                                                                              #
# Copyright(C) 2012 Parallel Dynamic Ltd.                                      #
# This file is licensed under the terms of the GNU General Public License      #
# version 2. This program  is licensed "as is" without any warranty of any 	   #
# kind whether express or implied.                                             #
################################################################################
require ${OEBASE}/arago-oe-dev/recipes/meta/meta-toolchain.bb


DISTRO_FEED_CONFIGS = arago-feed-configs

